<a href="https://colab.research.google.com/github/mopreni/data_science/blob/master/biblioteca_numpy_marisol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca Numpy

### Arreglos en NumPy

In [0]:
import numpy as np

data = np.random.randn(2, 3)

In [3]:
data

array([[ 0.5749528 , -0.49538492, -1.13239686],
       [-0.53820413,  1.17434192,  0.3575777 ]])

In [4]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [5]:
print(data)
data * 10,  data + data

[[ 0.5749528  -0.49538492 -1.13239686]
 [-0.53820413  1.17434192  0.3575777 ]]


(array([[  5.74952796,  -4.95384917, -11.32396856],
        [ -5.38204134,  11.74341922,   3.57577702]]),
 array([[ 1.14990559, -0.99076983, -2.26479371],
        [-1.07640827,  2.34868384,  0.7151554 ]]))

Estos arreglos de numpy podemos crearlos a partir de arreglos de python, por ejemplo:


In [0]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data)



Y ahora podemos utilizar operaciones como `shape` o `dim`

In [8]:
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Indexando arreglos

In [0]:
arr = np.arange(8)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr[5] # vemos el elemento en la posición 5 (contando desde el 0)

5

In [13]:
arr[2:5] # desde la pos 2 a la 4.

array([2, 3, 4])

In [0]:
arr[:] = 58 # Si asignamos un valor esto será _broadcasteado_ a todo el rango 

In [15]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

### Slicing

In [0]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])



In [17]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d[:1]

array([[1, 2, 3]])

In [19]:
arr2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr2d[1, :2]

array([4, 5])

In [21]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Filtros booleanos

In [22]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [23]:
arr2d < 2

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [24]:
arr2d[arr2d < 2]

array([1, 0, 0, 0, 0])

In [25]:
arr2d > 0

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [26]:
arr2d[arr2d > 0]

array([1, 4, 7, 8, 9])

### Funciones universales

In [27]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [29]:
np.abs([-2, 1, -3])

array([2, 1, 3])

In [30]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Funciones de agregación

In [34]:
arr = np.random.randn(5, 4)
arr

array([[ 0.85080233,  1.04318805, -0.34772408, -2.07916805],
       [ 0.46188015, -0.92144906, -0.78627572,  1.71245764],
       [ 0.14910332, -0.53606455, -1.32128158, -0.16061838],
       [ 1.18927612,  0.93905774, -1.71306018,  0.35297446],
       [-1.01975472,  0.54790042,  0.4344298 ,  0.09542324]])

In [35]:
arr.mean() # o np.mean(arr)

-0.05544515254431161

In [36]:
arr.sum()

-1.108903050886232